spring:
  application:
     name: DoctorVisitTracking
  datasource:
     url: jdbc:mysql://localhost:3306/doctor_visit_tracking
     username: root
     password: 1111
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration